# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_from', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('aspect', models.FloatField()),
                ('take_by_userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photoext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('lens', models.CharField(blank=True, max_length=100)),
                ('focal_length', models.CharField(blank=True, max_length=10)),
                ('iso', models.CharField(blank=True, max_length=10)),
                ('shutter_speed', models.CharField(blank=True, max_length=10)),
                ('aperture', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField()),
                ('location', models.FloatField()),
                ('taken_at', models.CharField(blank=True, max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('photoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Photodb')),
            ],
        ),
        migrations.CreateModel(
            name='Photofavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Photodb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
