# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photodb_photoext_photofavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoext',
            name='photoid',
        ),
        migrations.AddField(
            model_name='photodb',
            name='photoext',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Photoext'),
            preserve_default=False,
        ),
    ]
