# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photodb_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoext',
            name='location',
        ),
        migrations.AddField(
            model_name='photoext',
            name='longitude',
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photodb',
            name='aspect',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='width',
            field=models.FloatField(blank=True),
        ),
    ]
