# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170112_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodb',
            name='take_by_userid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
