# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170112_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodb',
            name='aspect',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
