# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170112_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodb',
            name='photoext',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Photoext'),
        ),
    ]
