# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170112_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoext',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
