# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoext',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
