# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170112_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoext',
            name='lens',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
