# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoext',
            name='aperture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='focal_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photoext',
            name='taken_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
